import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// Components
import Header from '../components/Header'
import Landing from '../components/Landing'
import Footer from '../components/Footer'


export default function Home() {
  return (
    <div className='parentdiv'>
      <Head>
        <title>Bona Wear | Truly Traceable Cashmere </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      
      <Header />
      <Landing />
      <Footer />
      
    </div>
  )
}
