import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// Components
import Header from '../components/Header'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bona Wear | Truly Traceable Cashmere </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      
      <Header />
      
    </div>
  )
}
